### ISSUE TITLE
Bug dans l'exercice Sd2aRacines

### ISSUE THREAD

**Issue by paternal** [Pyromaths/pyromaths#21]
Je suppose que l'on calcule la racine d'un nombre négatif.

~~~sh
$ ./utils/pyromaths-cli.py generate Sd2aRacines:4
Traceback (most recent call last):
  File "./utils/pyromaths-cli.py", line 28, in <module>
    runpy.run_module("pyromaths.cli", run_name="__main__")
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/louis/projets/pyromaths/src/src/pyromaths/cli/__main__.py", line 172, in <module>
    main()
  File "/home/louis/projets/pyromaths/src/src/pyromaths/cli/__main__.py", line 166, in main
    COMMANDS[options.command](options)
  File "/home/louis/projets/pyromaths/src/src/pyromaths/cli/__main__.py", line 145, in do_generate
    pipe=options.pipe,
  File "/home/louis/projets/pyromaths/src/src/pyromaths/ex/test.py", line 103, in generate
    'pipe': pipe,
  File "/home/louis/projets/pyromaths/src/src/pyromaths/outils/System.py", line 180, in creation
    f1.writelines(line + "\n" for line in exercice.tex_answer())
  File "/home/louis/projets/pyromaths/src/src/pyromaths/ex/lycee/SecondDegre.py", line 296, in tex_answer
    sol.extend(Priorites3.priorites(sol[0][0]))
  File "/home/louis/projets/pyromaths/src/src/pyromaths/outils/Priorites3.py", line 720, in priorites
    f = eval(calcul[0])
  File "<string>", line 1, in <module>
  File "/home/louis/projets/pyromaths/src/src/pyromaths/classes/SquareRoot.py", line 66, in __init__
    raise ValueError(u'Le radicande doit être un nombre positif.')
ValueError: <exception str() failed>
~~~

**Comment by JeromeO** [comment]
Corrigé dans https://github.com/Pyromaths/pyromaths/commit/2028ebac68dd2e19e5ea0858022ddf5ca6f92a7a
